from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

import duckdb

from synthetic_l2.reproducibility import reproducibility_fields


VIEW_SQL = {
    "stage_a1_quality": "read_csv_auto('outputs/stage_a1/data_quality_report.csv')",
    "stage_a1_horizon_coverage": "read_csv_auto('outputs/stage_a1/horizon_coverage.csv')",
    "stage_a1_open_window_coverage": "read_csv_auto('outputs/stage_a1/horizon_window_coverage_open_0915_0920.csv')",
    "horizon_readiness_summary": "read_csv_auto('outputs/horizon_readiness/horizon_readiness_summary.csv')",
    "horizon_readiness_one_second_symbols": "read_csv_auto('outputs/horizon_readiness/one_second_symbol_readiness.csv')",
    "phase1_summary": "read_csv_auto('outputs/phase1/phase1_feature_summary.csv')",
    "phase1_event_reconstruction_summary": "read_csv_auto('outputs/phase1/event_reconstruction/event_reconstruction_summary.csv')",
    "phase1_event_reconstruction_quality": "read_csv_auto('outputs/phase1/event_reconstruction/event_reconstruction_quality.csv')",
    "phase2_price": "read_csv_auto('outputs/phase2/price_tick_calibration.csv')",
    "phase2_activity": "read_csv_auto('outputs/phase2/activity_calibration.csv')",
    "phase2_depth": "read_csv_auto('outputs/phase2/depth_calibration.csv')",
    "phase2_trade_flow": "read_csv_auto('outputs/phase2/trade_flow_calibration.csv')",
    "phase3_daily": "read_csv_auto('outputs/phase3/daily_regime_observation.csv')",
    "phase3_intraday": "read_csv_auto('outputs/phase3/intraday_market_states.csv')",
    "phase3_ticker_states": "read_csv_auto('outputs/phase3/ticker_state_profile.csv')",
    "phase4_calendar": "read_csv_auto('outputs/phase4/scenario_calendar.csv')",
    "phase4_profile_summary": "read_csv_auto('outputs/phase4/profile_summary.csv')",
    "phase5_price_paths": "read_parquet('outputs/phase5/price_paths_5m.parquet')",
    "phase5_daily_price_summary": "read_csv_auto('outputs/phase5/daily_price_summary.csv')",
    "phase6_l2_book_states": "read_parquet('outputs/phase6/l2_book_states_5m.parquet')",
    "phase6_l2_book_summary": "read_csv_auto('outputs/phase6/l2_book_summary.csv')",
    "phase7_shock_library": "read_csv_auto('outputs/phase7/shock_library.csv')",
    "phase7_shock_type_summary": "read_csv_auto('outputs/phase7/shock_type_summary.csv')",
    "phase7_shock_day_summary": "read_csv_auto('outputs/phase7/shock_day_summary.csv')",
    "phase8_retail_feed_observations": "read_parquet('outputs/phase8/retail_feed_observations.parquet')",
    "phase8_retail_feed_dropped_events": "read_csv_auto('outputs/phase8/retail_feed_dropped_events.csv')",
    "phase8_feed_profile_summary": "read_csv_auto('outputs/phase8/feed_profile_summary.csv')",
    "phase9_tier_a_events": "read_parquet('outputs/phase9/tier_a/raw_synthetic_events.parquet')",
    "phase9_tier_b_l2_state": "read_parquet('outputs/phase9/tier_b/compact_l2_state.parquet')",
    "phase9_tier_c_features_5m": "read_parquet('outputs/phase9/tier_c/features_5m.parquet')",
    "phase9_tier_d_resampled_features_15m": "read_parquet('outputs/phase9/tier_d/resampled_features_15m.parquet')",
    "phase9_tier_d_resampled_summary": "read_csv_auto('outputs/phase9/tier_d/resampled_panel_summary.csv')",
    "phase10_measured_storage": "read_csv_auto('outputs/phase10/measured_storage_footprint.csv')",
    "phase10_real_symbol_storage": "read_csv_auto('outputs/phase10/real_sample_symbol_storage.csv')",
    "phase10_regime_storage_multipliers": "read_csv_auto('outputs/phase10/regime_storage_multipliers.csv')",
    "phase10_generation_profile_estimates": "read_csv_auto('outputs/phase10/generation_profile_size_estimates.csv')",
    "phase10_feature_interval_estimates": "read_csv_auto('outputs/phase10/feature_interval_size_estimates.csv')",
    "phase10_storage_inventory": "read_csv_auto('outputs/phase10/storage_inventory.csv')",
    "phase10_schema_physical_types": "read_csv_auto('outputs/phase10/schema_physical_types.csv')",
    "phase10_size_estimates": "read_csv_auto('outputs/phase10/size_estimates.csv')",
    "phase10_partition_recommendations": "read_csv_auto('outputs/phase10/partition_recommendations.csv')",
    "phase11_strategy_matrix": "read_csv_auto('outputs/phase11/strategy_validation_matrix.csv')",
    "phase11_baseline_matrix": "read_csv_auto('outputs/phase11/baseline_strategy_matrix.csv')",
    "phase11_feature_availability": "read_csv_auto('outputs/phase11/strategy_feature_availability.csv')",
    "phase11_signal_diagnostics": "read_csv_auto('outputs/phase11/strategy_signal_diagnostics.csv')",
    "phase11_strategy_module_registry": "read_csv_auto('outputs/phase11/strategy_module_registry.csv')",
    "phase11_strategy_module_coverage": "read_csv_auto('outputs/phase11/strategy_module_coverage.csv')",
    "phase12_execution_summary": "read_csv_auto('outputs/phase12/execution_summary.csv')",
    "phase12_execution_profiles": "read_csv_auto('outputs/phase12/execution_profiles.csv')",
    "phase12_cost_schedule": "read_csv_auto('outputs/phase12/cost_schedule.csv')",
    "phase12_charge_component_catalog": "read_csv_auto('outputs/phase12/charge_component_catalog.csv')",
    "phase12_representative_charge_scenarios": "read_csv_auto('outputs/phase12/representative_charge_scenarios.csv')",
    "phase12_full_run_risk_summary": "read_csv_auto('outputs/phase12/full_run_risk_summary.csv')",
    "phase12_full_run_lifecycle_risk_summary": "read_csv_auto('outputs/phase12/full_run_lifecycle_risk_summary.csv')",
    "phase12_full_run_lifecycle_daily_risk_summary": "read_csv_auto('outputs/phase12/full_run_lifecycle_daily_risk_summary.csv')",
    "phase12_full_run_lifecycle_risk_breach_severity": "read_csv_auto('outputs/phase12/full_run_lifecycle_risk_breach_severity.csv')",
    "phase12_full_run_lifecycle_risk_limit_sensitivity": "read_csv_auto('outputs/phase12/full_run_lifecycle_risk_limit_sensitivity.csv')",
    "phase12_full_run_risk_acceptance_readiness": "read_csv_auto('outputs/phase12/full_run_risk_acceptance_readiness.csv')",
    "phase12_trade_ledger_sample": "read_parquet('outputs/phase12/trade_ledger_sample.parquet')",
    "phase12_event_backtest_order_summary": "read_csv_auto('outputs/phase12/event_backtest_order_summary.csv')",
    "phase12_event_backtest_pnl_trace": "read_csv_auto('outputs/phase12/event_backtest_pnl_trace.csv')",
    "phase12_order_model_catalog": "read_csv_auto('outputs/phase12/order_model_catalog.csv')",
    "phase12_slippage_model_catalog": "read_csv_auto('outputs/phase12/slippage_model_catalog.csv')",
    "phase12_lifecycle_sample": "read_parquet('outputs/phase12_order_lifecycle/order_lifecycle_sample.parquet')",
    "phase12_partial_fill_summary": "read_csv_auto('outputs/phase12_order_lifecycle/partial_fill_summary.csv')",
    "phase12_risk_control_summary": "read_csv_auto('outputs/phase12_order_lifecycle/risk_control_summary.csv')",
    "phase12_fill_model_catalog": "read_csv_auto('outputs/phase12_order_lifecycle/fill_model_catalog.csv')",
    "phase13_data_splits": "read_csv_auto('outputs/phase13/data_splits.csv')",
    "phase13_seed_plan": "read_csv_auto('outputs/phase13/seed_plan.csv')",
    "phase13_walk_forward_windows": "read_csv_auto('outputs/phase13/walk_forward_windows.csv')",
    "phase13_parameter_grid": "read_csv_auto('outputs/phase13/parameter_grid.csv')",
    "phase13_negative_controls": "read_csv_auto('outputs/phase13/negative_controls.csv')",
    "phase13_experiment_registry": "read_csv_auto('outputs/phase13/experiment_registry.csv')",
    "phase13_experiment_run_ledger": "read_csv_auto('outputs/phase13/experiment_run_ledger.csv')",
    "phase13_experiment_run_summary": "read_csv_auto('outputs/phase13/experiment_run_summary.csv')",
    "phase13_negative_control_run_summary": "read_csv_auto('outputs/phase13/negative_control_run_summary.csv')",
    "phase13_profile_robustness_ledger": "read_csv_auto('outputs/phase13/experiment_profile_robustness_ledger.csv')",
    "phase13_profile_robustness_summary": "read_csv_auto('outputs/phase13/experiment_profile_robustness_summary.csv')",
    "phase13_robustness_dimension_summary": "read_csv_auto('outputs/phase13/robustness_dimension_summary.csv')",
    "phase13_robustness_acceptance_gap_ledger": "read_csv_auto('outputs/phase13/robustness_acceptance_gap_ledger.csv')",
    "phase14_quality_gate_summary": "read_csv_auto('outputs/phase14/quality_gate_summary.csv')",
    "phase14_quality_warning_triage": "read_csv_auto('outputs/phase14/quality_warning_triage.csv')",
    "phase14_holdout_generator_realism_summary": "read_csv_auto('outputs/phase14/holdout_generator_realism_summary.csv')",
    "phase14_realism_acceptance_gap_ledger": "read_csv_auto('outputs/phase14/realism_acceptance_gap_ledger.csv')",
    "phase14_real_5m_symbol_marginals": "read_csv_auto('outputs/phase14/real_5m_symbol_marginals.csv')",
    "phase14_level1_structural": "read_csv_auto('outputs/phase14/level1_structural.csv')",
    "phase14_level2_marginal": "read_csv_auto('outputs/phase14/level2_marginal.csv')",
    "phase14_level3_temporal": "read_csv_auto('outputs/phase14/level3_temporal.csv')",
    "phase14_level4_cross_sectional": "read_csv_auto('outputs/phase14/level4_cross_sectional.csv')",
    "phase14_level5_conditional": "read_csv_auto('outputs/phase14/level5_conditional.csv')",
    "phase14_level6_discriminator_proxy": "read_csv_auto('outputs/phase14/level6_discriminator_proxy.csv')",
    "phase14_level7_counterfactual": "read_csv_auto('outputs/phase14/level7_counterfactual.csv')",
    "phase15_gate_definitions": "read_csv_auto('outputs/phase15/gate_definitions.csv')",
    "phase15_strategy_gate_results": "read_csv_auto('outputs/phase15/strategy_gate_results.csv')",
    "phase15_strategy_acceptance_summary": "read_csv_auto('outputs/phase15/strategy_acceptance_summary.csv')",
    "phase15_acceptance_blockers": "read_csv_auto('outputs/phase15/acceptance_blockers.csv')",
    "phase16_metric_catalog": "read_csv_auto('outputs/phase16/metric_catalog.csv')",
    "phase16_predictive_metric_scoreboard": "read_csv_auto('outputs/phase16/predictive_metric_scoreboard.csv')",
    "phase16_predictive_proxy_diagnostics": "read_csv_auto('outputs/phase16/predictive_proxy_diagnostics.csv')",
    "phase16_predictive_signal_bucket_returns": "read_csv_auto('outputs/phase16/predictive_signal_bucket_returns.csv')",
    "phase16_predictive_brier_score_proxy": "read_csv_auto('outputs/phase16/predictive_brier_score_proxy.csv')",
    "phase16_predictive_calibration_curve_proxy": "read_csv_auto('outputs/phase16/predictive_calibration_curve_proxy.csv')",
    "phase16_predictive_baseline_comparison": "read_csv_auto('outputs/phase16/predictive_baseline_comparison.csv')",
    "phase16_predictive_holdout_stability": "read_csv_auto('outputs/phase16/predictive_holdout_stability.csv')",
    "phase16_predictive_holdout_stability_summary": "read_csv_auto('outputs/phase16/predictive_holdout_stability_summary.csv')",
    "phase16_feature_importance_stability_proxy": "read_csv_auto('outputs/phase16/feature_importance_stability_proxy.csv')",
    "phase16_predictive_promotion_falsification": "read_csv_auto('outputs/phase16/predictive_promotion_falsification.csv')",
    "phase16_predictive_acceptance_gap_ledger": "read_csv_auto('outputs/phase16/predictive_acceptance_gap_ledger.csv')",
    "phase16_trading_metric_scoreboard": "read_csv_auto('outputs/phase16/trading_metric_scoreboard.csv')",
    "phase16_economic_viability_frontier": "read_csv_auto('outputs/phase16/economic_viability_frontier.csv')",
    "phase16_risk_adjusted_economic_frontier": "read_csv_auto('outputs/phase16/risk_adjusted_economic_frontier.csv')",
    "phase16_broker_reconciliation_readiness": "read_csv_auto('outputs/phase16/broker_reconciliation_readiness.csv')",
    "phase16_economic_reconciliation_strategy_summary": "read_csv_auto('outputs/phase16/economic_reconciliation_strategy_summary.csv')",
    "phase16_economic_acceptance_gap_ledger": "read_csv_auto('outputs/phase16/economic_acceptance_gap_ledger.csv')",
    "phase16_markout_mae_mfe_summary": "read_csv_auto('outputs/phase16/markout_mae_mfe_summary.csv')",
    "phase16_breakdown_coverage": "read_csv_auto('outputs/phase16/breakdown_coverage.csv')",
    "phase16_strategy_metric_requirement_coverage": "read_csv_auto('outputs/phase16/strategy_metric_requirement_coverage.csv')",
    "phase17_work_package_registry": "read_csv_auto('outputs/phase17/work_package_registry.csv')",
    "phase17_deliverable_traceability": "read_csv_auto('outputs/phase17/deliverable_traceability.csv')",
    "phase17_implementation_gap_backlog": "read_csv_auto('outputs/phase17/implementation_gap_backlog.csv')",
    "phase20_acceptance_hardening_queue": "read_csv_auto('outputs/phase20/acceptance_hardening_queue.csv')",
    "phase20_acceptance_hardening_gate_summary": "read_csv_auto('outputs/phase20/acceptance_hardening_gate_summary.csv')",
    "phase20_acceptance_hardening_strategy_summary": "read_csv_auto('outputs/phase20/acceptance_hardening_strategy_summary.csv')",
    "phase20_acceptance_execution_roadmap": "read_csv_auto('outputs/phase20/acceptance_execution_roadmap.csv')",
    "phase20_acceptance_execution_milestones": "read_csv_auto('outputs/phase20/acceptance_execution_milestones.csv')",
    "phase20_risk_hardening_plan": "read_csv_auto('outputs/phase20/risk_hardening_plan.csv')",
    "phase20_risk_hardening_action_summary": "read_csv_auto('outputs/phase20/risk_hardening_action_summary.csv')",
    "phase20_economic_hardening_plan": "read_csv_auto('outputs/phase20/economic_hardening_plan.csv')",
    "phase20_economic_hardening_action_summary": "read_csv_auto('outputs/phase20/economic_hardening_action_summary.csv')",
    "phase20_predictive_hardening_plan": "read_csv_auto('outputs/phase20/predictive_hardening_plan.csv')",
    "phase20_predictive_hardening_action_summary": "read_csv_auto('outputs/phase20/predictive_hardening_action_summary.csv')",
    "phase20_robustness_hardening_plan": "read_csv_auto('outputs/phase20/robustness_hardening_plan.csv')",
    "phase20_robustness_hardening_action_summary": "read_csv_auto('outputs/phase20/robustness_hardening_action_summary.csv')",
    "phase20_realism_hardening_plan": "read_csv_auto('outputs/phase20/realism_hardening_plan.csv')",
    "phase20_realism_hardening_action_summary": "read_csv_auto('outputs/phase20/realism_hardening_action_summary.csv')",
    "phase20_m01_broker_evidence_import_checklist": "read_csv_auto('outputs/phase20_m01/broker_evidence_import_checklist.csv')",
    "phase20_m01_broker_evidence_schema": "read_csv_auto('outputs/phase20_m01/broker_evidence_schema.csv')",
    "phase20_m01_broker_reconciliation_test_catalog": "read_csv_auto('outputs/phase20_m01/broker_reconciliation_test_catalog.csv')",
    "phase20_m01_broker_external_gap_ledger": "read_csv_auto('outputs/phase20_m01/broker_external_gap_ledger.csv')",
    "phase20_m01_broker_external_gap_summary": "read_csv_auto('outputs/phase20_m01/broker_external_gap_summary.csv')",
    "phase20_m02_strategy_support_acceptance_criteria": "read_csv_auto('outputs/phase20_m02/strategy_support_acceptance_criteria.csv')",
    "phase20_m02_strategy_support_closure_ledger": "read_csv_auto('outputs/phase20_m02/strategy_support_closure_ledger.csv')",
    "phase20_m02_strategy_support_gap_summary": "read_csv_auto('outputs/phase20_m02/strategy_support_gap_summary.csv')",
    "phase20_m02_strategy_support_decision_summary": "read_csv_auto('outputs/phase20_m02/strategy_support_decision_summary.csv')",
    "validation_dashboard_summary": "read_csv_auto('outputs/dashboard/validation_dashboard_summary.csv')",
    "replay_validation_summary": "read_csv_auto('outputs/replay/replay_validation_summary.csv')",
    "phase18_stack_decisions": "read_csv_auto('outputs/phase18/stack_decisions.csv')",
    "phase18_dependency_availability": "read_csv_auto('outputs/phase18/dependency_availability.csv')",
    "phase19_reproducibility_required_fields": "read_csv_auto('outputs/phase19/reproducibility_required_fields.csv')",
    "phase19_manifest_field_audit": "read_csv_auto('outputs/phase19/manifest_field_audit.csv')",
    "phase19_artifact_reproducibility_summary": "read_csv_auto('outputs/phase19/artifact_reproducibility_summary.csv')",
    "phase19_reproducibility_gap_summary": "read_csv_auto('outputs/phase19/reproducibility_gap_summary.csv')",
    "phase19_reproducibility_remediation_plan": "read_csv_auto('outputs/phase19/reproducibility_remediation_plan.csv')",
    "phase19_reproducibility_remediation_summary": "read_csv_auto('outputs/phase19/reproducibility_remediation_summary.csv')",
    "phase19_normalized_manifest_overlay_summary": "read_csv_auto('outputs/phase19/normalized_manifest_overlay_summary.csv')",
    "phase19_normalized_manifest_field_sources": "read_csv_auto('outputs/phase19/normalized_manifest_field_sources.csv')",
    "compact_ticks": "read_parquet('outputs/stage_a1/compact_ticks_by_symbol/symbol=*/ticks.parquet', union_by_name=true)",
    "normalized_ticks": "read_parquet('outputs/phase1/normalized_ticks_by_symbol/symbol=*/normalized_ticks.parquet', union_by_name=true)",
    "received_tick_deltas": "read_parquet('outputs/phase1/received_tick_deltas_by_symbol/symbol=*/received_tick_deltas.parquet', union_by_name=true)",
}


def connect(workspace_db: Path) -> duckdb.DuckDBPyConnection:
    workspace_db.parent.mkdir(parents=True, exist_ok=True)
    con = duckdb.connect(str(workspace_db))
    con.execute("INSTALL json")
    con.execute("LOAD json")
    return con


def create_views(con: duckdb.DuckDBPyConnection) -> None:
    for view_name, source_sql in VIEW_SQL.items():
        con.execute(f"CREATE OR REPLACE VIEW {view_name} AS SELECT * FROM {source_sql}")


def run_validation(con: duckdb.DuckDBPyConnection) -> dict:
    checks = {
        "stage_a1_symbols": "SELECT count(*) FROM stage_a1_quality",
        "stage_a1_rows": "SELECT sum(row_count) FROM stage_a1_quality",
        "compact_tick_rows": "SELECT count(*) FROM compact_ticks",
        "normalized_tick_rows": "SELECT count(*) FROM normalized_ticks",
        "received_delta_rows": "SELECT count(*) FROM received_tick_deltas",
        "phase1_event_reconstruction_symbols": "SELECT count(*) FROM phase1_event_reconstruction_summary",
        "phase1_event_reconstruction_quality_rows": "SELECT count(*) FROM phase1_event_reconstruction_quality",
        "phase1_classified_trade_side_rows": "SELECT sum(classified_rows) FROM phase1_event_reconstruction_quality WHERE inference_area = 'trade_classification'",
        "phase1_replenishment_proxy_rows": "SELECT sum(classified_rows) FROM phase1_event_reconstruction_quality WHERE inference_area = 'replenishment'",
        "phase1_queue_event_proxy_rows": "SELECT sum(classified_rows) FROM phase1_event_reconstruction_quality WHERE inference_area = 'add_cancel_consume'",
        "phase2_symbols": "SELECT count(*) FROM phase2_price",
        "phase3_intraday_bins": "SELECT count(*) FROM phase3_intraday",
        "phase4_calendar_rows": "SELECT count(*) FROM phase4_calendar",
        "phase4_profiles": "SELECT count(distinct quarter_profile) FROM phase4_calendar",
        "phase5_price_bar_rows": "SELECT count(*) FROM phase5_price_paths",
        "phase5_daily_rows": "SELECT count(*) FROM phase5_daily_price_summary",
        "phase5_symbols": "SELECT count(distinct symbol) FROM phase5_price_paths",
        "phase6_l2_book_rows": "SELECT count(*) FROM phase6_l2_book_states",
        "phase6_symbols": "SELECT count(distinct symbol) FROM phase6_l2_book_states",
        "phase6_crossed_l1_rows": "SELECT count(*) FROM phase6_l2_book_states WHERE bid_px_1 >= ask_px_1",
        "phase7_shock_events": "SELECT count(*) FROM phase7_shock_library",
        "phase7_market_events": "SELECT count(*) FROM phase7_shock_library WHERE scope = 'market'",
        "phase7_ticker_events": "SELECT count(*) FROM phase7_shock_library WHERE scope = 'ticker'",
        "phase7_target_symbols": "SELECT count(distinct target) FROM phase7_shock_library WHERE scope = 'ticker'",
        "phase8_feed_observation_rows": "SELECT count(*) FROM phase8_retail_feed_observations",
        "phase8_feed_profiles": "SELECT count(distinct feed_profile) FROM phase8_retail_feed_observations",
        "phase8_dropped_rows": "SELECT count(*) FROM phase8_retail_feed_dropped_events",
        "phase8_duplicate_rows": "SELECT count(*) FROM phase8_retail_feed_observations WHERE is_duplicate = true",
        "phase9_tier_a_events": "SELECT count(*) FROM phase9_tier_a_events",
        "phase9_tier_b_rows": "SELECT count(*) FROM phase9_tier_b_l2_state",
        "phase9_tier_c_rows": "SELECT count(*) FROM phase9_tier_c_features_5m",
        "phase9_tier_d_resampled_rows": "SELECT count(*) FROM phase9_tier_d_resampled_features_15m",
        "phase9_tier_d_resampled_symbols": "SELECT count(distinct symbol) FROM phase9_tier_d_resampled_features_15m",
        "phase9_tier_d_resampled_interval_minutes": "SELECT max(target_interval_minutes) FROM phase9_tier_d_resampled_features_15m",
        "phase9_tier_d_incomplete_panels": "SELECT sum(CASE WHEN panel_complete THEN 0 ELSE 1 END) FROM phase9_tier_d_resampled_features_15m",
        "phase9_tier_b_crossed_l1_rows": "SELECT count(*) FROM phase9_tier_b_l2_state WHERE bid_px_1 >= ask_px_1",
        "phase10_measured_layers": "SELECT count(*) FROM phase10_measured_storage",
        "phase10_generation_profiles": "SELECT count(*) FROM phase10_generation_profile_estimates",
        "phase10_feature_intervals": "SELECT count(*) FROM phase10_feature_interval_estimates",
        "phase10_medium_estimated_total_gb": "SELECT estimated_total_gb FROM phase10_generation_profile_estimates WHERE profile = 'Medium'",
        "phase10_full_estimated_total_gb": "SELECT estimated_total_gb FROM phase10_generation_profile_estimates WHERE profile = 'Full'",
        "phase10_inventory_datasets": "SELECT count(*) FROM phase10_storage_inventory",
        "phase10_schema_columns": "SELECT count(*) FROM phase10_schema_physical_types",
        "phase10_partition_rows": "SELECT count(*) FROM phase10_partition_recommendations",
        "phase10_new_medium_total_gb": "SELECT total_gb FROM phase10_size_estimates WHERE profile = 'Medium'",
        "phase10_new_full_total_gb": "SELECT total_gb FROM phase10_size_estimates WHERE profile = 'Full'",
        "phase10_type_optimization_candidates": "SELECT count(*) FROM phase10_schema_physical_types WHERE recommended_type_note <> ''",
        "phase11_strategies": "SELECT count(*) FROM phase11_strategy_matrix",
        "phase11_baselines": "SELECT count(*) FROM phase11_baseline_matrix",
        "phase11_runnable_proxy_strategies": "SELECT count(*) FROM phase11_strategy_matrix WHERE support_level = 'runnable_proxy'",
        "phase11_partial_strategies": "SELECT count(*) FROM phase11_strategy_matrix WHERE support_level = 'partial_missing_required_features'",
        "phase11_not_supported_strategies": "SELECT count(*) FROM phase11_strategy_matrix WHERE support_level = 'not_supported_by_current_product'",
        "phase11_evaluated_rows": "SELECT max(rows_evaluated) FROM phase11_signal_diagnostics",
        "phase11_strategy_modules": "SELECT count(*) FROM phase11_strategy_module_registry",
        "phase11_implemented_proxy_modules": "SELECT count(*) FROM phase11_strategy_module_registry WHERE starts_with(implementation_status, 'implemented_proxy')",
        "phase11_promotion_ready_modules": "SELECT count(*) FROM phase11_strategy_module_registry WHERE promotion_ready = true",
        "phase11_module_coverage_checks": "SELECT count(*) FROM phase11_strategy_module_coverage",
        "phase11_module_coverage_passed": "SELECT count(*) FROM phase11_strategy_module_coverage WHERE passed = true",
        "phase12_summary_rows": "SELECT count(*) FROM phase12_execution_summary",
        "phase12_execution_profiles": "SELECT count(*) FROM phase12_execution_profiles",
        "phase12_strategies_simulated": "SELECT count(distinct strategy_id) FROM phase12_execution_summary",
        "phase12_total_trades": "SELECT sum(trades) FROM phase12_execution_summary",
        "phase12_trade_sample_rows": "SELECT count(*) FROM phase12_trade_ledger_sample",
        "phase12_cost_components": "SELECT count(*) FROM phase12_cost_schedule",
        "phase12_charge_formula_components": "SELECT count(*) FROM phase12_charge_component_catalog",
        "phase12_representative_charge_scenarios": "SELECT count(*) FROM phase12_representative_charge_scenarios",
        "phase12_full_run_risk_rows": "SELECT count(*) FROM phase12_full_run_risk_summary",
        "phase12_full_run_daily_loss_warn_days": "SELECT sum(daily_loss_warn_days) FROM phase12_full_run_risk_summary",
        "phase12_full_run_drawdown_warn_days": "SELECT sum(drawdown_warn_days) FROM phase12_full_run_risk_summary",
        "phase12_full_run_lifecycle_risk_rows": "SELECT count(*) FROM phase12_full_run_lifecycle_risk_summary",
        "phase12_full_run_lifecycle_daily_rows": "SELECT count(*) FROM phase12_full_run_lifecycle_daily_risk_summary",
        "phase12_full_run_lifecycle_fill_models": "SELECT count(distinct fill_model) FROM phase12_full_run_lifecycle_risk_summary",
        "phase12_full_run_lifecycle_daily_halt_rows": "SELECT sum(daily_halt_rows) FROM phase12_full_run_lifecycle_risk_summary",
        "phase12_full_run_lifecycle_position_breach_rows": "SELECT sum(position_limit_breach_rows) FROM phase12_full_run_lifecycle_risk_summary",
        "phase12_full_run_lifecycle_breach_severity_rows": "SELECT count(*) FROM phase12_full_run_lifecycle_risk_breach_severity",
        "phase12_full_run_lifecycle_risk_pass_candidate_rows": "SELECT count(*) FROM phase12_full_run_lifecycle_risk_breach_severity WHERE risk_pass_candidate_proxy = true",
        "phase12_full_run_lifecycle_high_severity_rows": "SELECT count(*) FROM phase12_full_run_lifecycle_risk_breach_severity WHERE risk_severity_band = 'high_proxy_breach_severity'",
        "phase12_full_run_lifecycle_risk_limit_sensitivity_rows": "SELECT count(*) FROM phase12_full_run_lifecycle_risk_limit_sensitivity",
        "phase12_full_run_lifecycle_risk_limit_profiles": "SELECT count(distinct risk_limit_profile) FROM phase12_full_run_lifecycle_risk_limit_sensitivity",
        "phase12_full_run_lifecycle_risk_limit_pass_rows": "SELECT count(*) FROM phase12_full_run_lifecycle_risk_limit_sensitivity WHERE risk_pass_candidate_under_limit_profile = true",
        "phase12_full_run_lifecycle_risk_limit_high_rows": "SELECT count(*) FROM phase12_full_run_lifecycle_risk_limit_sensitivity WHERE risk_limit_status = 'high_proxy_breach_under_limit_profile'",
        "phase12_full_run_risk_acceptance_readiness_rows": "SELECT count(*) FROM phase12_full_run_risk_acceptance_readiness",
        "phase12_full_run_risk_acceptance_readiness_open_rows": "SELECT count(*) FROM phase12_full_run_risk_acceptance_readiness WHERE acceptance_requirement_met = false",
        "phase12_full_run_risk_acceptance_readiness_proxy_rows": "SELECT count(*) FROM phase12_full_run_risk_acceptance_readiness WHERE proxy_evidence_available = true",
        "phase12_full_run_risk_acceptance_readiness_met_rows": "SELECT count(*) FROM phase12_full_run_risk_acceptance_readiness WHERE acceptance_requirement_met = true",
        "phase12_event_backtest_order_rows": "SELECT sum(orders) FROM phase12_event_backtest_order_summary",
        "phase12_event_backtest_order_models": "SELECT count(distinct order_model) FROM phase12_event_backtest_order_summary",
        "phase12_event_backtest_pnl_rows": "SELECT count(*) FROM phase12_event_backtest_pnl_trace",
        "phase12_order_model_catalog_rows": "SELECT count(*) FROM phase12_order_model_catalog",
        "phase12_slippage_model_catalog_rows": "SELECT count(*) FROM phase12_slippage_model_catalog",
        "phase12_lifecycle_rows": "SELECT count(*) FROM phase12_lifecycle_sample",
        "phase12_fill_models": "SELECT count(*) FROM phase12_fill_model_catalog",
        "phase12_partial_fill_summary_rows": "SELECT count(*) FROM phase12_partial_fill_summary",
        "phase12_risk_control_summary_rows": "SELECT count(*) FROM phase12_risk_control_summary",
        "phase12_position_limit_breach_rows": "SELECT sum(position_limit_breach_rows) FROM phase12_risk_control_summary",
        "phase12_daily_loss_limit_breach_rows": "SELECT sum(daily_loss_limit_breach_rows) FROM phase12_risk_control_summary",
        "phase13_split_rows": "SELECT count(*) FROM phase13_data_splits",
        "phase13_seed_rows": "SELECT count(*) FROM phase13_seed_plan",
        "phase13_initial_engineering_seeds": "SELECT count(*) FROM phase13_seed_plan WHERE initial_engineering_seed = true",
        "phase13_walk_forward_windows": "SELECT count(*) FROM phase13_walk_forward_windows",
        "phase13_parameter_sets": "SELECT count(*) FROM phase13_parameter_grid",
        "phase13_negative_controls": "SELECT count(*) FROM phase13_negative_controls",
        "phase13_planned_experiments": "SELECT count(*) FROM phase13_experiment_registry",
        "phase13_smoke_run_rows": "SELECT count(*) FROM phase13_experiment_run_ledger",
        "phase13_smoke_run_strategies": "SELECT count(distinct strategy_id) FROM phase13_experiment_run_ledger",
        "phase13_smoke_run_controls": "SELECT count(distinct control_id) FROM phase13_experiment_run_ledger",
        "phase13_smoke_run_summary_rows": "SELECT count(*) FROM phase13_experiment_run_summary",
        "phase13_profile_robustness_rows": "SELECT count(*) FROM phase13_profile_robustness_ledger",
        "phase13_profile_robustness_summary_rows": "SELECT count(*) FROM phase13_profile_robustness_summary",
        "phase13_profile_robustness_profiles": "SELECT count(distinct execution_profile) FROM phase13_profile_robustness_ledger",
        "phase13_all_profile_positive_strategies": "SELECT count(*) FROM phase13_profile_robustness_summary WHERE all_profiles_positive = true",
        "phase13_robustness_dimension_rows": "SELECT count(*) FROM phase13_robustness_dimension_summary",
        "phase13_robustness_dimension_registered_rows": "SELECT count(*) FROM phase13_robustness_dimension_summary WHERE registered_for_phase13_proxy = true",
        "phase13_robustness_holdout_proxy_rows": "SELECT count(*) FROM phase13_robustness_dimension_summary WHERE holdout_generator_profiles_present_in_proxy > 0",
        "phase13_robustness_acceptance_gap_rows": "SELECT count(*) FROM phase13_robustness_acceptance_gap_ledger",
        "phase13_robustness_acceptance_gap_open_rows": "SELECT count(*) FROM phase13_robustness_acceptance_gap_ledger WHERE acceptance_requirement_met = false",
        "phase13_robustness_acceptance_gap_met_rows": "SELECT count(*) FROM phase13_robustness_acceptance_gap_ledger WHERE acceptance_requirement_met = true",
        "phase13_acceptance_eligible_smoke_rows": "SELECT count(*) FROM phase13_experiment_run_ledger WHERE acceptance_eligible = true",
        "phase14_quality_checks": "SELECT count(*) FROM phase14_quality_gate_summary",
        "phase14_pass_checks": "SELECT count(*) FROM phase14_quality_gate_summary WHERE status = 'pass'",
        "phase14_warn_checks": "SELECT count(*) FROM phase14_quality_gate_summary WHERE status = 'warn'",
        "phase14_fail_checks": "SELECT count(*) FROM phase14_quality_gate_summary WHERE status = 'fail'",
        "phase14_warning_triage_rows": "SELECT count(*) FROM phase14_quality_warning_triage",
        "phase14_realism_blocking_warnings": "SELECT count(*) FROM phase14_quality_warning_triage WHERE acceptance_impact = 'blocks_realism_gate'",
        "phase14_holdout_generator_rows": "SELECT count(*) FROM phase14_holdout_generator_realism_summary",
        "phase14_holdout_proxy_available_rows": "SELECT count(*) FROM phase14_holdout_generator_realism_summary WHERE realism_status = 'holdout_proxy_available_not_acceptance'",
        "phase14_realism_acceptance_gap_rows": "SELECT count(*) FROM phase14_realism_acceptance_gap_ledger",
        "phase14_realism_acceptance_gap_open_rows": "SELECT count(*) FROM phase14_realism_acceptance_gap_ledger WHERE acceptance_requirement_met = false",
        "phase14_realism_acceptance_gap_proxy_rows": "SELECT count(*) FROM phase14_realism_acceptance_gap_ledger WHERE proxy_evidence_available = true",
        "phase14_realism_acceptance_gap_met_rows": "SELECT count(*) FROM phase14_realism_acceptance_gap_ledger WHERE acceptance_requirement_met = true",
        "phase14_real_5m_symbol_marginal_rows": "SELECT count(*) FROM phase14_real_5m_symbol_marginals",
        "phase15_gate_rows": "SELECT count(*) FROM phase15_strategy_gate_results",
        "phase15_promoted_strategies": "SELECT count(*) FROM phase15_strategy_acceptance_summary WHERE promotion_allowed = true",
        "phase15_blocked_strategies": "SELECT count(*) FROM phase15_strategy_acceptance_summary WHERE promotion_allowed = false",
        "phase15_blocker_rows": "SELECT count(*) FROM phase15_acceptance_blockers",
        "phase16_metric_catalog_rows": "SELECT count(*) FROM phase16_metric_catalog",
        "phase16_predictive_scoreboard_rows": "SELECT count(*) FROM phase16_predictive_metric_scoreboard",
        "phase16_predictive_proxy_rows": "SELECT count(*) FROM phase16_predictive_proxy_diagnostics",
        "phase16_predictive_signal_bucket_rows": "SELECT count(*) FROM phase16_predictive_signal_bucket_returns",
        "phase16_predictive_brier_score_rows": "SELECT count(*) FROM phase16_predictive_brier_score_proxy",
        "phase16_predictive_calibration_curve_rows": "SELECT count(*) FROM phase16_predictive_calibration_curve_proxy",
        "phase16_predictive_baseline_comparison_rows": "SELECT count(*) FROM phase16_predictive_baseline_comparison",
        "phase16_predictive_baseline_beating_rows": "SELECT count(*) FROM phase16_predictive_baseline_comparison WHERE predictive_baseline_status = 'beats_proxy_baselines_not_acceptance'",
        "phase16_predictive_holdout_stability_rows": "SELECT count(*) FROM phase16_predictive_holdout_stability",
        "phase16_predictive_holdout_stability_summary_rows": "SELECT count(*) FROM phase16_predictive_holdout_stability_summary",
        "phase16_predictive_holdout_all_cell_pass_rows": "SELECT count(*) FROM phase16_predictive_holdout_stability_summary WHERE worst_segment_status = 'all_cells_beat_local_majority_proxy'",
        "phase16_feature_importance_stability_rows": "SELECT count(*) FROM phase16_feature_importance_stability_proxy",
        "phase16_predictive_promotion_falsification_rows": "SELECT count(*) FROM phase16_predictive_promotion_falsification",
        "phase16_predictive_promotion_candidate_proxy_rows": "SELECT count(*) FROM phase16_predictive_promotion_falsification WHERE predictive_promotion_candidate_proxy = true",
        "phase16_predictive_promotion_falsified_rows": "SELECT count(*) FROM phase16_predictive_promotion_falsification WHERE falsification_status = 'falsified_for_predictive_promotion_under_current_proxy_evidence'",
        "phase16_predictive_acceptance_gap_rows": "SELECT count(*) FROM phase16_predictive_acceptance_gap_ledger",
        "phase16_predictive_acceptance_gap_open_rows": "SELECT count(*) FROM phase16_predictive_acceptance_gap_ledger WHERE acceptance_requirement_met = false",
        "phase16_predictive_acceptance_gap_proxy_rows": "SELECT count(*) FROM phase16_predictive_acceptance_gap_ledger WHERE proxy_evidence_available = true",
        "phase16_predictive_acceptance_gap_met_rows": "SELECT count(*) FROM phase16_predictive_acceptance_gap_ledger WHERE acceptance_requirement_met = true",
        "phase16_missing_predictive_metrics": "SELECT count(*) FROM phase16_metric_catalog WHERE metric_category = 'predictive' AND current_status = 'missing'",
        "phase16_missing_trading_metrics": "SELECT count(*) FROM phase16_metric_catalog WHERE metric_category = 'trading' AND current_status = 'missing'",
        "phase16_trading_scoreboard_rows": "SELECT count(*) FROM phase16_trading_metric_scoreboard",
        "phase16_economic_viability_rows": "SELECT count(*) FROM phase16_economic_viability_frontier",
        "phase16_economic_viability_net_positive_rows": "SELECT count(*) FROM phase16_economic_viability_frontier WHERE net_positive_proxy = true",
        "phase16_economic_viability_retail_stress_positive_rows": "SELECT count(*) FROM phase16_economic_viability_frontier WHERE net_positive_proxy = true AND retail_or_stress_profile = true",
        "phase16_risk_adjusted_economic_rows": "SELECT count(*) FROM phase16_risk_adjusted_economic_frontier",
        "phase16_risk_adjusted_economic_joint_pass_rows": "SELECT count(*) FROM phase16_risk_adjusted_economic_frontier WHERE net_positive_and_risk_pass_proxy = true",
        "phase16_risk_adjusted_economic_retail_stress_joint_pass_rows": "SELECT count(*) FROM phase16_risk_adjusted_economic_frontier WHERE retail_stress_net_positive_and_risk_pass_proxy = true",
        "phase16_risk_adjusted_economic_positive_but_risk_blocked_rows": "SELECT count(*) FROM phase16_risk_adjusted_economic_frontier WHERE risk_adjusted_frontier_status = 'economic_positive_but_risk_blocked_proxy'",
        "phase16_broker_reconciliation_rows": "SELECT count(*) FROM phase16_broker_reconciliation_readiness",
        "phase16_broker_reconciliation_proxy_formula_ready_rows": "SELECT count(*) FROM phase16_broker_reconciliation_readiness WHERE proxy_formula_available_now = true",
        "phase16_broker_reconciliation_contract_note_ready_rows": "SELECT count(*) FROM phase16_broker_reconciliation_readiness WHERE broker_contract_note_available_now = true",
        "phase16_economic_reconciliation_strategy_rows": "SELECT count(*) FROM phase16_economic_reconciliation_strategy_summary",
        "phase16_economic_reconciliation_ready_strategies": "SELECT count(*) FROM phase16_economic_reconciliation_strategy_summary WHERE economic_acceptance_ready_now = true",
        "phase16_economic_acceptance_gap_rows": "SELECT count(*) FROM phase16_economic_acceptance_gap_ledger",
        "phase16_economic_acceptance_gap_open_rows": "SELECT count(*) FROM phase16_economic_acceptance_gap_ledger WHERE acceptance_requirement_met = false",
        "phase16_economic_acceptance_gap_proxy_rows": "SELECT count(*) FROM phase16_economic_acceptance_gap_ledger WHERE proxy_evidence_available = true",
        "phase16_economic_acceptance_gap_met_rows": "SELECT count(*) FROM phase16_economic_acceptance_gap_ledger WHERE acceptance_requirement_met = true",
        "phase16_markout_summary_rows": "SELECT count(*) FROM phase16_markout_mae_mfe_summary",
        "phase16_markout_sample_trades": "SELECT sum(markout_sample_trades) FROM phase16_markout_mae_mfe_summary",
        "phase16_adverse_selection_metric_status": "SELECT current_status FROM phase16_metric_catalog WHERE metric_name = 'adverse_selection'",
        "phase16_mae_mfe_metric_status": "SELECT current_status FROM phase16_metric_catalog WHERE metric_name = 'mae_mfe'",
        "phase16_breakdown_rows": "SELECT count(*) FROM phase16_breakdown_coverage",
        "phase16_acceptance_grade_metrics": "SELECT count(*) FROM phase16_metric_catalog WHERE acceptance_eligible_now = true",
        "phase16_missing_or_proxy_metrics": "SELECT count(*) FROM phase16_metric_catalog WHERE acceptance_eligible_now = false",
        "phase17_work_packages": "SELECT count(*) FROM phase17_work_package_registry",
        "phase17_deliverables": "SELECT count(*) FROM phase17_deliverable_traceability",
        "phase17_implemented_deliverables": "SELECT count(*) FROM phase17_deliverable_traceability WHERE implementation_status = 'implemented'",
        "phase17_proxy_or_partial_deliverables": "SELECT count(*) FROM phase17_deliverable_traceability WHERE implementation_status IN ('implemented_proxy', 'partial_current', 'partial_proxy')",
        "phase17_missing_deliverables": "SELECT count(*) FROM phase17_deliverable_traceability WHERE implementation_status = 'missing'",
        "phase17_blocked_work_packages": "SELECT count(*) FROM phase17_work_package_registry WHERE current_status = 'blocked_by_missing_deliverables'",
        "phase17_p0_gaps": "SELECT count(*) FROM phase17_implementation_gap_backlog WHERE priority = 'P0'",
        "phase20_hardening_queue_rows": "SELECT count(*) FROM phase20_acceptance_hardening_queue",
        "phase20_hardening_gate_rows": "SELECT count(*) FROM phase20_acceptance_hardening_gate_summary",
        "phase20_hardening_strategy_rows": "SELECT count(*) FROM phase20_acceptance_hardening_strategy_summary",
        "phase20_acceptance_execution_roadmap_rows": "SELECT count(*) FROM phase20_acceptance_execution_roadmap",
        "phase20_acceptance_execution_milestone_rows": "SELECT count(*) FROM phase20_acceptance_execution_milestones",
        "phase20_acceptance_execution_roadmap_proxy_rows": "SELECT count(*) FROM phase20_acceptance_execution_roadmap WHERE proxy_evidence_available = true",
        "phase20_acceptance_execution_roadmap_missing_rows": "SELECT count(*) FROM phase20_acceptance_execution_roadmap WHERE proxy_evidence_available = false",
        "phase20_acceptance_execution_roadmap_met_rows": "SELECT count(*) FROM phase20_acceptance_execution_roadmap WHERE acceptance_requirement_met = true",
        "phase20_risk_hardening_plan_rows": "SELECT count(*) FROM phase20_risk_hardening_plan",
        "phase20_risk_hardening_proxy_rows": "SELECT count(*) FROM phase20_risk_hardening_plan WHERE proxy_evidence_available = true",
        "phase20_risk_hardening_missing_rows": "SELECT count(*) FROM phase20_risk_hardening_plan WHERE proxy_evidence_available = false",
        "phase20_risk_hardening_met_rows": "SELECT count(*) FROM phase20_risk_hardening_plan WHERE acceptance_requirement_met = true",
        "phase20_risk_hardening_action_rows": "SELECT count(*) FROM phase20_risk_hardening_action_summary",
        "phase20_economic_hardening_plan_rows": "SELECT count(*) FROM phase20_economic_hardening_plan",
        "phase20_economic_hardening_proxy_rows": "SELECT count(*) FROM phase20_economic_hardening_plan WHERE proxy_evidence_available = true",
        "phase20_economic_hardening_missing_rows": "SELECT count(*) FROM phase20_economic_hardening_plan WHERE proxy_evidence_available = false",
        "phase20_economic_hardening_met_rows": "SELECT count(*) FROM phase20_economic_hardening_plan WHERE acceptance_requirement_met = true",
        "phase20_economic_hardening_action_rows": "SELECT count(*) FROM phase20_economic_hardening_action_summary",
        "phase20_predictive_hardening_plan_rows": "SELECT count(*) FROM phase20_predictive_hardening_plan",
        "phase20_predictive_hardening_proxy_rows": "SELECT count(*) FROM phase20_predictive_hardening_plan WHERE proxy_evidence_available = true",
        "phase20_predictive_hardening_missing_rows": "SELECT count(*) FROM phase20_predictive_hardening_plan WHERE proxy_evidence_available = false",
        "phase20_predictive_hardening_met_rows": "SELECT count(*) FROM phase20_predictive_hardening_plan WHERE acceptance_requirement_met = true",
        "phase20_predictive_hardening_action_rows": "SELECT count(*) FROM phase20_predictive_hardening_action_summary",
        "phase20_robustness_hardening_plan_rows": "SELECT count(*) FROM phase20_robustness_hardening_plan",
        "phase20_robustness_hardening_proxy_rows": "SELECT count(*) FROM phase20_robustness_hardening_plan WHERE proxy_evidence_available = true",
        "phase20_robustness_hardening_missing_rows": "SELECT count(*) FROM phase20_robustness_hardening_plan WHERE proxy_evidence_available = false",
        "phase20_robustness_hardening_met_rows": "SELECT count(*) FROM phase20_robustness_hardening_plan WHERE acceptance_requirement_met = true",
        "phase20_robustness_hardening_action_rows": "SELECT count(*) FROM phase20_robustness_hardening_action_summary",
        "phase20_realism_hardening_plan_rows": "SELECT count(*) FROM phase20_realism_hardening_plan",
        "phase20_realism_hardening_proxy_rows": "SELECT count(*) FROM phase20_realism_hardening_plan WHERE proxy_evidence_available = true",
        "phase20_realism_hardening_missing_rows": "SELECT count(*) FROM phase20_realism_hardening_plan WHERE proxy_evidence_available = false",
        "phase20_realism_hardening_met_rows": "SELECT count(*) FROM phase20_realism_hardening_plan WHERE acceptance_requirement_met = true",
        "phase20_realism_hardening_action_rows": "SELECT count(*) FROM phase20_realism_hardening_action_summary",
        "phase20_acceptance_ready_rows": "SELECT count(*) FROM phase20_acceptance_hardening_queue WHERE acceptance_ready_now = true",
        "phase20_top_priority_gate_rows": "SELECT blocked_strategies FROM phase20_acceptance_hardening_gate_summary WHERE priority_rank = (SELECT min(priority_rank) FROM phase20_acceptance_hardening_gate_summary)",
        "phase20_m01_broker_required_external_files": "SELECT count(*) FROM phase20_m01_broker_evidence_import_checklist",
        "phase20_m01_broker_available_external_files": "SELECT count(*) FROM phase20_m01_broker_evidence_import_checklist WHERE file_exists_now = true",
        "phase20_m01_broker_schema_rows": "SELECT count(*) FROM phase20_m01_broker_evidence_schema",
        "phase20_m01_broker_reconciliation_test_rows": "SELECT count(*) FROM phase20_m01_broker_reconciliation_test_catalog",
        "phase20_m01_broker_external_gap_rows": "SELECT count(*) FROM phase20_m01_broker_external_gap_ledger",
        "phase20_m01_broker_external_gap_acceptance_met_rows": "SELECT count(*) FROM phase20_m01_broker_external_gap_ledger WHERE acceptance_requirement_met_after_contract = true",
        "phase20_m02_strategy_support_criteria_rows": "SELECT count(*) FROM phase20_m02_strategy_support_acceptance_criteria",
        "phase20_m02_strategy_support_closure_rows": "SELECT count(*) FROM phase20_m02_strategy_support_closure_ledger",
        "phase20_m02_strategy_support_feature_engineering_rows": "SELECT count(*) FROM phase20_m02_strategy_support_closure_ledger WHERE feature_engineering_required = true",
        "phase20_m02_strategy_support_classification_rows": "SELECT count(*) FROM phase20_m02_strategy_support_closure_ledger WHERE classification_required = true",
        "phase20_m02_strategy_support_acceptance_upgrade_rows": "SELECT count(*) FROM phase20_m02_strategy_support_closure_ledger WHERE acceptance_upgrade_required = true",
        "phase20_m02_strategy_support_acceptance_met_rows": "SELECT count(*) FROM phase20_m02_strategy_support_closure_ledger WHERE acceptance_requirement_met_after_contract = true",
        "validation_dashboard_summary_rows": "SELECT count(*) FROM validation_dashboard_summary",
        "validation_dashboard_promoted_strategies": "SELECT value FROM validation_dashboard_summary WHERE metric = 'promoted_strategies'",
        "validation_dashboard_p1_gaps": "SELECT value FROM validation_dashboard_summary WHERE metric = 'p1_gaps'",
        "replay_validation_tiers": "SELECT count(*) FROM replay_validation_summary",
        "replay_validation_deterministic_tiers": "SELECT count(*) FROM replay_validation_summary WHERE deterministic_ordering = true",
        "phase18_stack_decision_rows": "SELECT count(*) FROM phase18_stack_decisions",
        "phase18_dependency_rows": "SELECT count(*) FROM phase18_dependency_availability",
        "phase18_required_now_dependencies": "SELECT count(*) FROM phase18_dependency_availability WHERE requirement_status = 'required_now'",
        "phase18_missing_required_now_dependencies": "SELECT count(*) FROM phase18_dependency_availability WHERE requirement_status = 'required_now' AND available_now = false",
        "phase18_deferred_or_optional_items": "SELECT count(*) FROM phase18_stack_decisions WHERE decision_status IN ('optional_later', 'defer')",
        "horizon_readiness_rows": "SELECT count(*) FROM horizon_readiness_summary",
        "horizon_readiness_one_second_symbols": "SELECT count(*) FROM horizon_readiness_one_second_symbols",
        "horizon_readiness_event_driven_1s_symbols": "SELECT count(*) FROM horizon_readiness_one_second_symbols WHERE event_driven_1s_ready = true",
        "horizon_readiness_dense_1s_symbols": "SELECT count(*) FROM horizon_readiness_one_second_symbols WHERE dense_1s_ready = true",
        "phase19_required_fields": "SELECT count(*) FROM phase19_reproducibility_required_fields",
        "phase19_audited_artifacts": "SELECT count(*) FROM phase19_artifact_reproducibility_summary",
        "phase19_field_checks": "SELECT count(*) FROM phase19_manifest_field_audit",
        "phase19_exact_regeneration_ready_artifacts": "SELECT count(*) FROM phase19_artifact_reproducibility_summary WHERE exact_regeneration_ready = true",
        "phase19_artifacts_with_missing_fields": "SELECT count(*) FROM phase19_artifact_reproducibility_summary WHERE missing_fields > 0",
        "phase19_manifest_missing_or_unreadable_artifacts": "SELECT count(*) FROM phase19_artifact_reproducibility_summary WHERE manifest_missing_or_unreadable_fields > 0",
        "phase19_gap_rows": "SELECT count(*) FROM phase19_reproducibility_gap_summary",
        "phase19_remediation_rows": "SELECT count(*) FROM phase19_reproducibility_remediation_plan",
        "phase19_remediation_summary_rows": "SELECT count(*) FROM phase19_reproducibility_remediation_summary",
        "phase19_normalized_overlay_artifacts": "SELECT count(*) FROM phase19_normalized_manifest_overlay_summary",
        "phase19_normalized_overlay_ready_artifacts": "SELECT count(*) FROM phase19_normalized_manifest_overlay_summary WHERE exact_field_overlay_ready = true",
        "phase19_normalizer_default_fields": "SELECT sum(normalizer_default_fields) FROM phase19_normalized_manifest_overlay_summary",
        "phase19_source_or_alias_fields": "SELECT sum(source_manifest_exact_or_alias_fields) FROM phase19_normalized_manifest_overlay_summary",
        "phase19_generator_field_rows": "SELECT count(*) FROM phase19_reproducibility_remediation_plan WHERE remediation_status = 'add_field_in_generator'",
        "phase19_alias_normalization_rows": "SELECT count(*) FROM phase19_reproducibility_remediation_plan WHERE remediation_status = 'normalize_alias_to_exact_field'",
        "phase19_recover_manifest_rows": "SELECT count(*) FROM phase19_reproducibility_remediation_plan WHERE remediation_status = 'recover_or_rerun_manifest'",
    }
    results = {name: con.execute(sql).fetchone()[0] for name, sql in checks.items()}
    results["phase4_days_per_profile"] = con.execute(
        "SELECT quarter_profile, count(*) AS days FROM phase4_calendar GROUP BY 1 ORDER BY 1"
    ).fetchall()
    results["dense_full_session_1s_below_90_symbols"] = con.execute(
        "SELECT count(*) FROM stage_a1_horizon_coverage WHERE horizon_ms = 1000 AND supported_for_resampling = false"
    ).fetchone()[0]
    results["dense_full_session_5s_supported_symbols"] = con.execute(
        "SELECT count(*) FROM stage_a1_horizon_coverage WHERE horizon_ms = 5000 AND supported_for_resampling = true"
    ).fetchone()[0]
    results["open_window_dense_1s_supported_symbols"] = con.execute(
        "SELECT count(*) FROM stage_a1_open_window_coverage WHERE horizon_ms = 1000 AND supported_dense_regular_panel = true"
    ).fetchone()[0]
    results["open_window_event_driven_1s_supported_symbols"] = con.execute(
        "SELECT count(*) FROM stage_a1_open_window_coverage WHERE horizon_ms = 1000 AND supports_event_driven_1s = true"
    ).fetchone()[0]
    return results


def write_report(output_dir: Path, workspace_db: Path, validation: dict) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    generated_utc = datetime.now(timezone.utc).isoformat()
    manifest = {
        "generated_utc": generated_utc,
        "duckdb_database": str(workspace_db),
        "storage_decision": "Parquet remains the durable storage; DuckDB is the analytic query layer over Parquet views.",
        "validation": validation,
        "views": sorted(VIEW_SQL),
    }
    manifest.update(
        reproducibility_fields(
            artifact_id="duckdb",
            generated_utc=generated_utc,
            inputs={"registered_views": sorted(VIEW_SQL)},
            parameters={
                "storage_decision": manifest["storage_decision"],
                "view_count": len(VIEW_SQL),
            },
            outputs={
                "duckdb_database": str(workspace_db),
                "manifest": str(output_dir / "duckdb_workspace_manifest.json"),
                "report": str(output_dir / "duckdb_workspace_report.md"),
            },
            random_seed="not_applicable_deterministic_duckdb_view_registration",
            scenario_ids="current_workspace_registered_phase_views",
            cost_model_version="outputs/phase12/cost_schedule.csv_and_zerodha_order_formula_v2_or_not_applicable",
            latency_model_version="outputs/phase12/execution_profiles.csv_or_not_applicable",
        )
    )
    (output_dir / "duckdb_workspace_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    day_rows = "\n".join(f"| {profile} | {days} |" for profile, days in validation["phase4_days_per_profile"])
    lines = [
        "# DuckDB Workspace Report",
        "",
        f"Generated UTC: {manifest['generated_utc']}",
        "",
        "## Storage Decision",
        "",
        "Use Parquet as durable storage and DuckDB as the local analytic query engine over registered views.",
        "Use SQLite only later if we need a small transactional run registry or manual annotation database.",
        "",
        "## Validation",
        "",
        f"- Stage A1 symbols: {validation['stage_a1_symbols']}",
        f"- Stage A1 rows: {validation['stage_a1_rows']}",
        f"- Compact tick rows: {validation['compact_tick_rows']}",
        f"- Normalized tick rows: {validation['normalized_tick_rows']}",
        f"- Received delta rows: {validation['received_delta_rows']}",
        f"- Phase 1 event reconstruction symbols: {validation['phase1_event_reconstruction_symbols']}",
        f"- Phase 1 event reconstruction quality rows: {validation['phase1_event_reconstruction_quality_rows']}",
        f"- Phase 1 classified trade-side rows: {validation['phase1_classified_trade_side_rows']}",
        f"- Phase 1 replenishment proxy rows: {validation['phase1_replenishment_proxy_rows']}",
        f"- Phase 1 queue-event proxy rows: {validation['phase1_queue_event_proxy_rows']}",
        f"- Phase 2 symbols: {validation['phase2_symbols']}",
        f"- Phase 3 intraday bins: {validation['phase3_intraday_bins']}",
        f"- Phase 4 calendar rows: {validation['phase4_calendar_rows']}",
        f"- Phase 4 profiles: {validation['phase4_profiles']}",
        f"- Phase 5 price bar rows: {validation['phase5_price_bar_rows']}",
        f"- Phase 5 daily rows: {validation['phase5_daily_rows']}",
        f"- Phase 5 symbols: {validation['phase5_symbols']}",
        f"- Phase 6 L2 book rows: {validation['phase6_l2_book_rows']}",
        f"- Phase 6 symbols: {validation['phase6_symbols']}",
        f"- Phase 6 crossed L1 rows: {validation['phase6_crossed_l1_rows']}",
        f"- Phase 7 shock events: {validation['phase7_shock_events']}",
        f"- Phase 7 market events: {validation['phase7_market_events']}",
        f"- Phase 7 ticker events: {validation['phase7_ticker_events']}",
        f"- Phase 7 target symbols: {validation['phase7_target_symbols']}",
        f"- Phase 8 feed observation rows: {validation['phase8_feed_observation_rows']}",
        f"- Phase 8 feed profiles: {validation['phase8_feed_profiles']}",
        f"- Phase 8 dropped rows: {validation['phase8_dropped_rows']}",
        f"- Phase 8 duplicate rows: {validation['phase8_duplicate_rows']}",
        f"- Phase 9 Tier A events: {validation['phase9_tier_a_events']}",
        f"- Phase 9 Tier B rows: {validation['phase9_tier_b_rows']}",
        f"- Phase 9 Tier C rows: {validation['phase9_tier_c_rows']}",
        f"- Phase 9 Tier D 15-minute resampled rows: {validation['phase9_tier_d_resampled_rows']}",
        f"- Phase 9 Tier D symbols: {validation['phase9_tier_d_resampled_symbols']}",
        f"- Phase 9 Tier D interval minutes: {validation['phase9_tier_d_resampled_interval_minutes']}",
        f"- Phase 9 Tier D incomplete panels: {validation['phase9_tier_d_incomplete_panels']}",
        f"- Phase 9 Tier B crossed L1 rows: {validation['phase9_tier_b_crossed_l1_rows']}",
        f"- Phase 10 measured storage layers: {validation['phase10_measured_layers']}",
        f"- Phase 10 generation profiles: {validation['phase10_generation_profiles']}",
        f"- Phase 10 feature intervals: {validation['phase10_feature_intervals']}",
        f"- Phase 10 Medium estimated total GB: {validation['phase10_medium_estimated_total_gb']}",
        f"- Phase 10 Full estimated total GB: {validation['phase10_full_estimated_total_gb']}",
        f"- Phase 10 consolidated inventory datasets: {validation['phase10_inventory_datasets']}",
        f"- Phase 10 consolidated schema columns: {validation['phase10_schema_columns']}",
        f"- Phase 10 partition recommendation rows: {validation['phase10_partition_rows']}",
        f"- Phase 10 consolidated Medium estimated total GB: {validation['phase10_new_medium_total_gb']:.2f}",
        f"- Phase 10 consolidated Full estimated total GB: {validation['phase10_new_full_total_gb']:.2f}",
        f"- Phase 10 type optimization candidates: {validation['phase10_type_optimization_candidates']}",
        f"- Phase 11 strategies: {validation['phase11_strategies']}",
        f"- Phase 11 baselines: {validation['phase11_baselines']}",
        f"- Phase 11 runnable proxy strategies: {validation['phase11_runnable_proxy_strategies']}",
        f"- Phase 11 partial/missing-feature strategies: {validation['phase11_partial_strategies']}",
        f"- Phase 11 unsupported-by-current-product strategies: {validation['phase11_not_supported_strategies']}",
        f"- Phase 11 rows evaluated per strategy: {validation['phase11_evaluated_rows']}",
        f"- Phase 11 strategy modules: {validation['phase11_strategy_modules']}",
        f"- Phase 11 implemented proxy modules: {validation['phase11_implemented_proxy_modules']}",
        f"- Phase 11 promotion-ready modules: {validation['phase11_promotion_ready_modules']}",
        f"- Phase 11 module coverage checks: {validation['phase11_module_coverage_checks']}",
        f"- Phase 11 module coverage checks passed: {validation['phase11_module_coverage_passed']}",
        f"- Phase 12 execution summary rows: {validation['phase12_summary_rows']}",
        f"- Phase 12 execution profiles: {validation['phase12_execution_profiles']}",
        f"- Phase 12 strategies simulated: {validation['phase12_strategies_simulated']}",
        f"- Phase 12 total simulated trades: {validation['phase12_total_trades']}",
        f"- Phase 12 trade sample rows: {validation['phase12_trade_sample_rows']}",
        f"- Phase 12 cost components: {validation['phase12_cost_components']}",
        f"- Phase 12 full-run risk rows: {validation['phase12_full_run_risk_rows']}",
        f"- Phase 12 full-run daily-loss warn days: {validation['phase12_full_run_daily_loss_warn_days']}",
        f"- Phase 12 full-run drawdown warn days: {validation['phase12_full_run_drawdown_warn_days']}",
        f"- Phase 12 full-run lifecycle risk rows: {validation['phase12_full_run_lifecycle_risk_rows']}",
        f"- Phase 12 full-run lifecycle daily rows: {validation['phase12_full_run_lifecycle_daily_rows']}",
        f"- Phase 12 full-run lifecycle fill models: {validation['phase12_full_run_lifecycle_fill_models']}",
        f"- Phase 12 full-run lifecycle daily halt rows: {validation['phase12_full_run_lifecycle_daily_halt_rows']}",
        f"- Phase 12 full-run lifecycle position-breach rows: {validation['phase12_full_run_lifecycle_position_breach_rows']}",
        f"- Phase 12 full-run lifecycle breach-severity rows: {validation['phase12_full_run_lifecycle_breach_severity_rows']}",
        f"- Phase 12 full-run lifecycle risk-pass candidate rows: {validation['phase12_full_run_lifecycle_risk_pass_candidate_rows']}",
        f"- Phase 12 full-run lifecycle high-severity rows: {validation['phase12_full_run_lifecycle_high_severity_rows']}",
        f"- Phase 12 full-run lifecycle risk-limit sensitivity rows: {validation['phase12_full_run_lifecycle_risk_limit_sensitivity_rows']}",
        f"- Phase 12 full-run lifecycle risk-limit profiles: {validation['phase12_full_run_lifecycle_risk_limit_profiles']}",
        f"- Phase 12 full-run lifecycle risk-limit pass rows: {validation['phase12_full_run_lifecycle_risk_limit_pass_rows']}",
        f"- Phase 12 full-run lifecycle risk-limit high-severity rows: {validation['phase12_full_run_lifecycle_risk_limit_high_rows']}",
        f"- Phase 12 full-run risk acceptance readiness rows: {validation['phase12_full_run_risk_acceptance_readiness_rows']}",
        f"- Phase 12 open full-run risk acceptance readiness rows: {validation['phase12_full_run_risk_acceptance_readiness_open_rows']}",
        f"- Phase 12 full-run risk readiness rows with proxy evidence: {validation['phase12_full_run_risk_acceptance_readiness_proxy_rows']}",
        f"- Phase 12 met full-run risk acceptance readiness rows: {validation['phase12_full_run_risk_acceptance_readiness_met_rows']}",
        f"- Phase 12 event-backtest order rows: {validation['phase12_event_backtest_order_rows']}",
        f"- Phase 12 event-backtest order models: {validation['phase12_event_backtest_order_models']}",
        f"- Phase 12 event-backtest P&L rows: {validation['phase12_event_backtest_pnl_rows']}",
        f"- Phase 12 order model catalog rows: {validation['phase12_order_model_catalog_rows']}",
        f"- Phase 12 slippage model catalog rows: {validation['phase12_slippage_model_catalog_rows']}",
        f"- Phase 12 lifecycle rows: {validation['phase12_lifecycle_rows']}",
        f"- Phase 12 fill models: {validation['phase12_fill_models']}",
        f"- Phase 12 partial-fill summary rows: {validation['phase12_partial_fill_summary_rows']}",
        f"- Phase 12 risk-control summary rows: {validation['phase12_risk_control_summary_rows']}",
        f"- Phase 12 position-limit breach rows: {validation['phase12_position_limit_breach_rows']}",
        f"- Phase 12 daily-loss-limit breach rows: {validation['phase12_daily_loss_limit_breach_rows']}",
        f"- Phase 13 split rows: {validation['phase13_split_rows']}",
        f"- Phase 13 seed rows: {validation['phase13_seed_rows']}",
        f"- Phase 13 initial engineering seeds: {validation['phase13_initial_engineering_seeds']}",
        f"- Phase 13 walk-forward windows: {validation['phase13_walk_forward_windows']}",
        f"- Phase 13 parameter sets: {validation['phase13_parameter_sets']}",
        f"- Phase 13 negative controls: {validation['phase13_negative_controls']}",
        f"- Phase 13 planned experiment registry rows: {validation['phase13_planned_experiments']}",
        f"- Phase 13 proxy smoke run rows: {validation['phase13_smoke_run_rows']}",
        f"- Phase 13 proxy smoke strategies: {validation['phase13_smoke_run_strategies']}",
        f"- Phase 13 proxy smoke controls: {validation['phase13_smoke_run_controls']}",
        f"- Phase 13 proxy smoke summary rows: {validation['phase13_smoke_run_summary_rows']}",
        f"- Phase 13 profile robustness rows: {validation['phase13_profile_robustness_rows']}",
        f"- Phase 13 profile robustness summary rows: {validation['phase13_profile_robustness_summary_rows']}",
        f"- Phase 13 profile robustness profiles: {validation['phase13_profile_robustness_profiles']}",
        f"- Phase 13 all-profile-positive strategies: {validation['phase13_all_profile_positive_strategies']}",
        f"- Phase 13 robustness dimension rows: {validation['phase13_robustness_dimension_rows']}",
        f"- Phase 13 robustness dimension registered rows: {validation['phase13_robustness_dimension_registered_rows']}",
        f"- Phase 13 robustness holdout proxy rows: {validation['phase13_robustness_holdout_proxy_rows']}",
        f"- Phase 13 robustness acceptance gap rows: {validation['phase13_robustness_acceptance_gap_rows']}",
        f"- Phase 13 open robustness acceptance gap rows: {validation['phase13_robustness_acceptance_gap_open_rows']}",
        f"- Phase 13 met robustness acceptance requirement rows: {validation['phase13_robustness_acceptance_gap_met_rows']}",
        f"- Phase 13 acceptance-eligible smoke rows: {validation['phase13_acceptance_eligible_smoke_rows']}",
        f"- Phase 14 quality checks: {validation['phase14_quality_checks']}",
        f"- Phase 14 pass checks: {validation['phase14_pass_checks']}",
        f"- Phase 14 warn checks: {validation['phase14_warn_checks']}",
        f"- Phase 14 fail checks: {validation['phase14_fail_checks']}",
        f"- Phase 14 warning triage rows: {validation['phase14_warning_triage_rows']}",
        f"- Phase 14 realism-blocking warnings: {validation['phase14_realism_blocking_warnings']}",
        f"- Phase 14 holdout generator rows: {validation['phase14_holdout_generator_rows']}",
        f"- Phase 14 holdout proxy available rows: {validation['phase14_holdout_proxy_available_rows']}",
        f"- Phase 14 realism acceptance gap rows: {validation['phase14_realism_acceptance_gap_rows']}",
        f"- Phase 14 open realism acceptance gap rows: {validation['phase14_realism_acceptance_gap_open_rows']}",
        f"- Phase 14 realism acceptance gap rows with proxy evidence: {validation['phase14_realism_acceptance_gap_proxy_rows']}",
        f"- Phase 14 met realism acceptance gap rows: {validation['phase14_realism_acceptance_gap_met_rows']}",
        f"- Phase 14 real 5-minute symbol marginal rows: {validation['phase14_real_5m_symbol_marginal_rows']}",
        f"- Phase 15 gate rows: {validation['phase15_gate_rows']}",
        f"- Phase 15 promoted strategies: {validation['phase15_promoted_strategies']}",
        f"- Phase 15 blocked strategies: {validation['phase15_blocked_strategies']}",
        f"- Phase 15 blocker rows: {validation['phase15_blocker_rows']}",
        f"- Phase 16 metric catalog rows: {validation['phase16_metric_catalog_rows']}",
        f"- Phase 16 predictive scoreboard rows: {validation['phase16_predictive_scoreboard_rows']}",
        f"- Phase 16 predictive proxy rows: {validation['phase16_predictive_proxy_rows']}",
        f"- Phase 16 predictive signal bucket rows: {validation['phase16_predictive_signal_bucket_rows']}",
        f"- Phase 16 Brier score proxy rows: {validation['phase16_predictive_brier_score_rows']}",
        f"- Phase 16 calibration-curve proxy rows: {validation['phase16_predictive_calibration_curve_rows']}",
        f"- Phase 16 predictive baseline comparison rows: {validation['phase16_predictive_baseline_comparison_rows']}",
        f"- Phase 16 predictive baseline-beating rows: {validation['phase16_predictive_baseline_beating_rows']}",
        f"- Phase 16 predictive holdout stability rows: {validation['phase16_predictive_holdout_stability_rows']}",
        f"- Phase 16 predictive holdout stability summary rows: {validation['phase16_predictive_holdout_stability_summary_rows']}",
        f"- Phase 16 predictive holdout all-cell-pass rows: {validation['phase16_predictive_holdout_all_cell_pass_rows']}",
        f"- Phase 16 feature-importance stability rows: {validation['phase16_feature_importance_stability_rows']}",
        f"- Phase 16 predictive promotion falsification rows: {validation['phase16_predictive_promotion_falsification_rows']}",
        f"- Phase 16 predictive promotion candidate proxy rows: {validation['phase16_predictive_promotion_candidate_proxy_rows']}",
        f"- Phase 16 predictive promotion falsified rows: {validation['phase16_predictive_promotion_falsified_rows']}",
        f"- Phase 16 predictive acceptance gap rows: {validation['phase16_predictive_acceptance_gap_rows']}",
        f"- Phase 16 open predictive acceptance gap rows: {validation['phase16_predictive_acceptance_gap_open_rows']}",
        f"- Phase 16 predictive acceptance gap rows with proxy evidence: {validation['phase16_predictive_acceptance_gap_proxy_rows']}",
        f"- Phase 16 met predictive acceptance gap rows: {validation['phase16_predictive_acceptance_gap_met_rows']}",
        f"- Phase 16 missing predictive metrics: {validation['phase16_missing_predictive_metrics']}",
        f"- Phase 16 missing trading metrics: {validation['phase16_missing_trading_metrics']}",
        f"- Phase 16 trading scoreboard rows: {validation['phase16_trading_scoreboard_rows']}",
        f"- Phase 16 economic viability rows: {validation['phase16_economic_viability_rows']}",
        f"- Phase 16 economic viability net-positive rows: {validation['phase16_economic_viability_net_positive_rows']}",
        f"- Phase 16 economic viability retail/stress positive rows: {validation['phase16_economic_viability_retail_stress_positive_rows']}",
        f"- Phase 16 risk-adjusted economic rows: {validation['phase16_risk_adjusted_economic_rows']}",
        f"- Phase 16 risk-adjusted economic joint-pass rows: {validation['phase16_risk_adjusted_economic_joint_pass_rows']}",
        f"- Phase 16 risk-adjusted economic retail/stress joint-pass rows: {validation['phase16_risk_adjusted_economic_retail_stress_joint_pass_rows']}",
        f"- Phase 16 economic-positive but risk-blocked rows: {validation['phase16_risk_adjusted_economic_positive_but_risk_blocked_rows']}",
        f"- Phase 16 broker reconciliation readiness rows: {validation['phase16_broker_reconciliation_rows']}",
        f"- Phase 16 broker reconciliation proxy-formula-ready rows: {validation['phase16_broker_reconciliation_proxy_formula_ready_rows']}",
        f"- Phase 16 broker reconciliation contract-note-ready rows: {validation['phase16_broker_reconciliation_contract_note_ready_rows']}",
        f"- Phase 16 economic reconciliation strategy rows: {validation['phase16_economic_reconciliation_strategy_rows']}",
        f"- Phase 16 economic reconciliation ready strategies: {validation['phase16_economic_reconciliation_ready_strategies']}",
        f"- Phase 16 economic acceptance gap rows: {validation['phase16_economic_acceptance_gap_rows']}",
        f"- Phase 16 open economic acceptance gap rows: {validation['phase16_economic_acceptance_gap_open_rows']}",
        f"- Phase 16 economic acceptance gap rows with proxy evidence: {validation['phase16_economic_acceptance_gap_proxy_rows']}",
        f"- Phase 16 met economic acceptance gap rows: {validation['phase16_economic_acceptance_gap_met_rows']}",
        f"- Phase 16 markout/MAE/MFE summary rows: {validation['phase16_markout_summary_rows']}",
        f"- Phase 16 markout sample trades: {validation['phase16_markout_sample_trades']}",
        f"- Phase 16 adverse-selection metric status: {validation['phase16_adverse_selection_metric_status']}",
        f"- Phase 16 MAE/MFE metric status: {validation['phase16_mae_mfe_metric_status']}",
        f"- Phase 16 breakdown rows: {validation['phase16_breakdown_rows']}",
        f"- Phase 16 acceptance-grade metrics: {validation['phase16_acceptance_grade_metrics']}",
        f"- Phase 16 non-acceptance-grade metrics: {validation['phase16_missing_or_proxy_metrics']}",
        f"- Phase 17 work packages: {validation['phase17_work_packages']}",
        f"- Phase 17 deliverables: {validation['phase17_deliverables']}",
        f"- Phase 17 implemented deliverables: {validation['phase17_implemented_deliverables']}",
        f"- Phase 17 proxy/partial deliverables: {validation['phase17_proxy_or_partial_deliverables']}",
        f"- Phase 17 missing deliverables: {validation['phase17_missing_deliverables']}",
        f"- Phase 17 blocked work packages: {validation['phase17_blocked_work_packages']}",
        f"- Phase 17 P0 gaps: {validation['phase17_p0_gaps']}",
        f"- Phase 20 acceptance hardening queue rows: {validation['phase20_hardening_queue_rows']}",
        f"- Phase 20 acceptance hardening gate rows: {validation['phase20_hardening_gate_rows']}",
        f"- Phase 20 acceptance hardening strategy rows: {validation['phase20_hardening_strategy_rows']}",
        f"- Phase 20 acceptance execution roadmap rows: {validation['phase20_acceptance_execution_roadmap_rows']}",
        f"- Phase 20 acceptance execution milestone rows: {validation['phase20_acceptance_execution_milestone_rows']}",
        f"- Phase 20 acceptance execution roadmap rows with proxy evidence: {validation['phase20_acceptance_execution_roadmap_proxy_rows']}",
        f"- Phase 20 acceptance execution roadmap rows missing required evidence: {validation['phase20_acceptance_execution_roadmap_missing_rows']}",
        f"- Phase 20 met acceptance execution roadmap rows: {validation['phase20_acceptance_execution_roadmap_met_rows']}",
        f"- Phase 20 risk hardening plan rows: {validation['phase20_risk_hardening_plan_rows']}",
        f"- Phase 20 risk hardening rows with proxy evidence: {validation['phase20_risk_hardening_proxy_rows']}",
        f"- Phase 20 risk hardening rows missing required evidence: {validation['phase20_risk_hardening_missing_rows']}",
        f"- Phase 20 met risk hardening rows: {validation['phase20_risk_hardening_met_rows']}",
        f"- Phase 20 risk hardening action rows: {validation['phase20_risk_hardening_action_rows']}",
        f"- Phase 20 economic hardening plan rows: {validation['phase20_economic_hardening_plan_rows']}",
        f"- Phase 20 economic hardening rows with proxy evidence: {validation['phase20_economic_hardening_proxy_rows']}",
        f"- Phase 20 economic hardening rows missing required evidence: {validation['phase20_economic_hardening_missing_rows']}",
        f"- Phase 20 met economic hardening rows: {validation['phase20_economic_hardening_met_rows']}",
        f"- Phase 20 economic hardening action rows: {validation['phase20_economic_hardening_action_rows']}",
        f"- Phase 20 predictive hardening plan rows: {validation['phase20_predictive_hardening_plan_rows']}",
        f"- Phase 20 predictive hardening rows with proxy evidence: {validation['phase20_predictive_hardening_proxy_rows']}",
        f"- Phase 20 predictive hardening rows missing required evidence: {validation['phase20_predictive_hardening_missing_rows']}",
        f"- Phase 20 met predictive hardening rows: {validation['phase20_predictive_hardening_met_rows']}",
        f"- Phase 20 predictive hardening action rows: {validation['phase20_predictive_hardening_action_rows']}",
        f"- Phase 20 robustness hardening plan rows: {validation['phase20_robustness_hardening_plan_rows']}",
        f"- Phase 20 robustness hardening rows with proxy evidence: {validation['phase20_robustness_hardening_proxy_rows']}",
        f"- Phase 20 robustness hardening rows missing required evidence: {validation['phase20_robustness_hardening_missing_rows']}",
        f"- Phase 20 met robustness hardening rows: {validation['phase20_robustness_hardening_met_rows']}",
        f"- Phase 20 robustness hardening action rows: {validation['phase20_robustness_hardening_action_rows']}",
        f"- Phase 20 realism hardening plan rows: {validation['phase20_realism_hardening_plan_rows']}",
        f"- Phase 20 realism hardening rows with proxy evidence: {validation['phase20_realism_hardening_proxy_rows']}",
        f"- Phase 20 realism hardening rows missing required evidence: {validation['phase20_realism_hardening_missing_rows']}",
        f"- Phase 20 met realism hardening rows: {validation['phase20_realism_hardening_met_rows']}",
        f"- Phase 20 realism hardening action rows: {validation['phase20_realism_hardening_action_rows']}",
        f"- Phase 20 acceptance-ready queue rows: {validation['phase20_acceptance_ready_rows']}",
        f"- Phase 20 top-priority gate blocked strategies: {validation['phase20_top_priority_gate_rows']}",
        f"- Phase 20 M01 broker required external files: {validation['phase20_m01_broker_required_external_files']}",
        f"- Phase 20 M01 broker available external files: {validation['phase20_m01_broker_available_external_files']}",
        f"- Phase 20 M01 broker evidence schema rows: {validation['phase20_m01_broker_schema_rows']}",
        f"- Phase 20 M01 broker reconciliation test rows: {validation['phase20_m01_broker_reconciliation_test_rows']}",
        f"- Phase 20 M01 broker external gap rows: {validation['phase20_m01_broker_external_gap_rows']}",
        f"- Phase 20 M01 broker external gap acceptance-met rows: {validation['phase20_m01_broker_external_gap_acceptance_met_rows']}",
        f"- Phase 20 M02 strategy support criteria rows: {validation['phase20_m02_strategy_support_criteria_rows']}",
        f"- Phase 20 M02 strategy support closure rows: {validation['phase20_m02_strategy_support_closure_rows']}",
        f"- Phase 20 M02 strategy support feature-engineering rows: {validation['phase20_m02_strategy_support_feature_engineering_rows']}",
        f"- Phase 20 M02 strategy support classification rows: {validation['phase20_m02_strategy_support_classification_rows']}",
        f"- Phase 20 M02 strategy support acceptance-upgrade rows: {validation['phase20_m02_strategy_support_acceptance_upgrade_rows']}",
        f"- Phase 20 M02 strategy support acceptance-met rows: {validation['phase20_m02_strategy_support_acceptance_met_rows']}",
        f"- Validation dashboard summary rows: {validation['validation_dashboard_summary_rows']}",
        f"- Validation dashboard promoted strategies: {validation['validation_dashboard_promoted_strategies']}",
        f"- Validation dashboard P1 gaps: {validation['validation_dashboard_p1_gaps']}",
        f"- Replay validation tiers: {validation['replay_validation_tiers']}",
        f"- Replay deterministic tiers: {validation['replay_validation_deterministic_tiers']}",
        f"- Phase 18 stack decision rows: {validation['phase18_stack_decision_rows']}",
        f"- Phase 18 dependency rows: {validation['phase18_dependency_rows']}",
        f"- Phase 18 required-now dependencies: {validation['phase18_required_now_dependencies']}",
        f"- Phase 18 missing required-now dependencies: {validation['phase18_missing_required_now_dependencies']}",
        f"- Phase 18 deferred/optional stack items: {validation['phase18_deferred_or_optional_items']}",
        f"- Horizon readiness decision rows: {validation['horizon_readiness_rows']}",
        f"- Horizon readiness one-second symbol rows: {validation['horizon_readiness_one_second_symbols']}",
        f"- Horizon readiness event-driven 1s symbols: {validation['horizon_readiness_event_driven_1s_symbols']}",
        f"- Horizon readiness dense 1s symbols: {validation['horizon_readiness_dense_1s_symbols']}",
        f"- Phase 19 required fields: {validation['phase19_required_fields']}",
        f"- Phase 19 audited artifacts: {validation['phase19_audited_artifacts']}",
        f"- Phase 19 field checks: {validation['phase19_field_checks']}",
        f"- Phase 19 exact-regeneration-ready artifacts: {validation['phase19_exact_regeneration_ready_artifacts']}",
        f"- Phase 19 artifacts with missing fields: {validation['phase19_artifacts_with_missing_fields']}",
        f"- Phase 19 manifest-missing/unreadable artifacts: {validation['phase19_manifest_missing_or_unreadable_artifacts']}",
        f"- Phase 19 gap rows: {validation['phase19_gap_rows']}",
        f"- Phase 19 remediation rows: {validation['phase19_remediation_rows']}",
        f"- Phase 19 remediation summary rows: {validation['phase19_remediation_summary_rows']}",
        f"- Phase 19 normalized overlay artifacts: {validation['phase19_normalized_overlay_artifacts']}",
        f"- Phase 19 normalized overlay-ready artifacts: {validation['phase19_normalized_overlay_ready_artifacts']}",
        f"- Phase 19 normalizer-default fields: {validation['phase19_normalizer_default_fields']}",
        f"- Phase 19 source-or-alias fields: {validation['phase19_source_or_alias_fields']}",
        f"- Phase 19 add-field-in-generator rows: {validation['phase19_generator_field_rows']}",
        f"- Phase 19 alias-normalization rows: {validation['phase19_alias_normalization_rows']}",
        f"- Phase 19 recover/rerun-manifest rows: {validation['phase19_recover_manifest_rows']}",
        f"- Dense full-session 1s below 90% symbols: {validation['dense_full_session_1s_below_90_symbols']}",
        f"- Dense full-session 5s supported symbols: {validation['dense_full_session_5s_supported_symbols']}",
        f"- Open 09:15-09:20 dense 1s supported symbols: {validation['open_window_dense_1s_supported_symbols']}",
        f"- Open 09:15-09:20 event-driven 1s supported symbols: {validation['open_window_event_driven_1s_supported_symbols']}",
        "",
        "## Phase 4 Days Per Profile",
        "",
        "| Profile | Days |",
        "| --- | --- |",
        day_rows,
        "",
    ]
    (output_dir / "duckdb_workspace_report.md").write_text("\n".join(lines), encoding="utf-8")


def run(workspace_db: Path, output_dir: Path) -> None:
    con = connect(workspace_db)
    try:
        create_views(con)
        validation = run_validation(con)
    finally:
        con.close()
    write_report(output_dir, workspace_db, validation)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create DuckDB views over SyntheticL2 Parquet/CSV outputs.")
    parser.add_argument("--workspace-db", type=Path, default=Path("outputs/duckdb/synthetic_l2.duckdb"))
    parser.add_argument("--output-dir", type=Path, default=Path("outputs/duckdb"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    run(args.workspace_db, args.output_dir)


if __name__ == "__main__":
    main()
