from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from synthetic_l2.phase25_event_replay_expansion import _markdown_table
from synthetic_l2.phase254_materialize_richer_raw_top5_depth_event_bars import read_csv
from synthetic_l2.phase274_focused_capital_followthrough_interpretation import metric_value
from synthetic_l2.phase441_external_catalyst_full_depth_confirmation import (
    build_acceptance as build_phase441_style_acceptance,
    build_gates as build_phase441_style_gates,
    evaluate,
)
from synthetic_l2.phase443_external_catalyst_continuation_precommit import NEXT_ACTION as PHASE443_NEXT_ACTION
from synthetic_l2.reproducibility import reproducibility_fields
from synthetic_l2.zerodha_costs import ZERODHA_EQUITY_INTRADAY_NSE_MODEL_VERSION


DEFAULT_PHASE443_DIR = Path("outputs/phase443")
DEFAULT_PHASE387_DIR = Path("outputs/phase387")
DEFAULT_OUTPUT_DIR = Path("outputs/phase444")

THESIS_ID = "P444_EXTERNAL_CATALYST_CONTINUATION_FULL_DEPTH_EXECUTION"
NEXT_ACTION = "interpret_phase444_external_catalyst_continuation_no_paper_live"


def continuation_evaluate(events: pd.DataFrame, grid: pd.DataFrame, panel: str, *, reversal_control: bool = False, l1_only: bool = False, time_shift: bool = False) -> tuple[pd.DataFrame, pd.DataFrame]:
    ledger, summary = evaluate(events, grid, panel, side_flip=not reversal_control, l1_only=l1_only, time_shift=time_shift)
    # Phase441 evaluate implements reversal as primary and side_flip as continuation.
    # For Phase444, side_flip=True is therefore the primary continuation source.
    return ledger, summary


def build_gates(summary: pd.DataFrame, l1_summary: pd.DataFrame, reversal_summary: pd.DataFrame, shift_summary: pd.DataFrame, source_events: pd.DataFrame) -> pd.DataFrame:
    gates = build_phase441_style_gates(summary, l1_summary, reversal_summary, shift_summary, source_events)
    gates = gates.copy()
    gates["gate_id"] = gates["gate_id"].str.replace("P441", "P444", regex=False)
    gates.loc[gates["gate_id"].eq("P444_PHASE440_PRECOMMIT_USED"), "gate_id"] = "P444_PHASE443_PRECOMMIT_USED"
    gates.loc[gates["gate_id"].eq("P444_PHASE443_PRECOMMIT_USED"), "observed_value"] = PHASE443_NEXT_ACTION
    gates.loc[gates["gate_id"].eq("P444_PHASE443_PRECOMMIT_USED"), "required_value"] = "phase443_next_action"
    gates.loc[gates["gate_id"].eq("P444_SIDE_FLIP_CONTROL_NOT_DOMINANT"), "gate_id"] = "P444_REVERSAL_CONTROL_NOT_DOMINANT"
    gates.loc[gates["gate_id"].eq("P444_TIME_SHIFT_CONTROL_NOT_DOMINANT"), "gate_id"] = "P444_TIME_SHIFT_CONTROL_NOT_DOMINANT"
    return gates


def build_acceptance(events: pd.DataFrame, summary: pd.DataFrame, gates: pd.DataFrame) -> pd.DataFrame:
    acc = build_phase441_style_acceptance(events, summary, gates).copy()
    acc["metric"] = acc["metric"].str.replace("phase441_external_catalyst_full_depth_complete", "phase444_external_catalyst_continuation_complete", regex=False)
    acc["metric"] = acc["metric"].str.replace("phase441_thesis_id", "phase444_thesis_id", regex=False)
    acc["metric"] = acc["metric"].str.replace("phase441_", "phase444_", regex=False)
    acc.loc[acc["metric"].eq("phase444_thesis_id"), "value"] = THESIS_ID
    acc.loc[acc["metric"].eq("phase444_external_catalyst_continuation_complete"), "description"] = "Phase444 execution completed"
    acc.loc[acc["metric"].eq("phase444_next_best_action"), "value"] = NEXT_ACTION
    return acc


def write_report(output_dir: Path, acceptance: pd.DataFrame, summary: pd.DataFrame, controls: pd.DataFrame, gates: pd.DataFrame) -> None:
    lines = [
        "# Phase444 External Catalyst Continuation Full-Depth Execution",
        "",
        "Phase444 executes the Phase443 catalyst-continuation source. Continuation follows the catalyst impulse; reversal is retained only as a control.",
        "",
        "The run uses local Phase387 event-feature evidence and records the fixed-horizon limitation inherited from that ledger.",
        "",
        "## Acceptance Summary",
        "",
        _markdown_table(acceptance),
        "",
        "## Scenario Summary",
        "",
        _markdown_table(summary),
        "",
        "## Controls For Best Scenario",
        "",
        _markdown_table(controls),
        "",
        "## Gate Evaluation",
        "",
        _markdown_table(gates),
        "",
        "Boundary: no strategy promotion, paper/live acceptance or deployable profitability claim is generated by Phase444.",
    ]
    (output_dir / "phase444_external_catalyst_continuation_full_depth_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def run(phase443_dir: Path = DEFAULT_PHASE443_DIR, phase387_dir: Path = DEFAULT_PHASE387_DIR, output_dir: Path = DEFAULT_OUTPUT_DIR) -> pd.DataFrame:
    output_dir.mkdir(parents=True, exist_ok=True)
    generated_utc = datetime.now(timezone.utc).isoformat()
    phase443 = read_csv(phase443_dir / "phase443_acceptance_summary.csv")
    if str(metric_value(phase443, "phase443_next_best_action", "")) != PHASE443_NEXT_ACTION:
        raise ValueError("Phase444 requires Phase443 execution allowance.")
    grid = read_csv(phase443_dir / "phase443_catalyst_continuation_scenario_grid.csv")
    events = read_csv(phase387_dir / "phase387_event_feature_ledger.csv")
    ready = events[events["status"].astype(str).eq("ready")].copy()
    ledger, summary = continuation_evaluate(ready, grid, "external_catalyst_continuation_full_depth")
    l1_ledger, l1_summary = continuation_evaluate(ready, grid, "l1_only_ablation", l1_only=True)
    reversal_ledger, reversal_summary = continuation_evaluate(ready, grid, "reversal_control", reversal_control=True)
    shift_ledger, shift_summary = continuation_evaluate(ready, grid, "time_shifted_catalyst", time_shift=True)
    best_sid = str(summary[pd.to_numeric(summary["completed_round_trips"], errors="coerce").fillna(0).gt(0)].sort_values("annualized_return_pct", ascending=False).iloc[0]["scenario_id"])
    controls = pd.DataFrame(
        [
            {"control": "l1_only", **l1_summary[l1_summary["scenario_id"].astype(str).eq(best_sid)].iloc[0].to_dict()},
            {"control": "reversal", **reversal_summary[reversal_summary["scenario_id"].astype(str).eq(best_sid)].iloc[0].to_dict()},
            {"control": "time_shifted_catalyst", **shift_summary[shift_summary["scenario_id"].astype(str).eq(best_sid)].iloc[0].to_dict()},
        ]
    )
    gates = build_gates(summary, l1_summary, reversal_summary, shift_summary, ready)
    acceptance = build_acceptance(ready, summary, gates)
    summary.to_csv(output_dir / "phase444_scenario_summary.csv", index=False)
    ledger.to_csv(output_dir / "phase444_trade_ledger.csv", index=False)
    controls.to_csv(output_dir / "phase444_best_scenario_controls.csv", index=False)
    gates.to_csv(output_dir / "phase444_gate_evaluation.csv", index=False)
    acceptance.to_csv(output_dir / "phase444_acceptance_summary.csv", index=False)
    write_report(output_dir, acceptance, summary, controls, gates)
    manifest = {
        "generated_utc": generated_utc,
        "scope": "phase444_external_catalyst_continuation_full_depth",
        **reproducibility_fields(
            artifact_id="phase444_external_catalyst_continuation_full_depth",
            generated_utc=generated_utc,
            inputs={"phase443_grid": str(phase443_dir / "phase443_catalyst_continuation_scenario_grid.csv"), "phase387_events": str(phase387_dir / "phase387_event_feature_ledger.csv")},
            parameters={"thesis_id": THESIS_ID, "source_horizon": "phase387_feature_ledger_fixed_horizon_seconds"},
            outputs={"acceptance_summary": str(output_dir / "phase444_acceptance_summary.csv")},
            cost_model_version=ZERODHA_EQUITY_INTRADAY_NSE_MODEL_VERSION,
            latency_model_version="phase387_event_feature_fixed_horizon",
        ),
    }
    (output_dir / "phase444_external_catalyst_continuation_full_depth_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return acceptance


def main() -> None:
    parser = argparse.ArgumentParser(description="Run Phase444 external catalyst continuation full-depth execution.")
    parser.add_argument("--phase443-dir", type=Path, default=DEFAULT_PHASE443_DIR)
    parser.add_argument("--phase387-dir", type=Path, default=DEFAULT_PHASE387_DIR)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()
    acceptance = run(args.phase443_dir, args.phase387_dir, args.output_dir)
    print(acceptance.to_string(index=False))


if __name__ == "__main__":
    main()
